Add privacy policy
mello-app/static-website pull request #10
Opened 2021-01-13 19:43 UTC by doamatto

2021-01-14 15:15 UTC, doamatto commented
In a daring feat, I've once again ignored the fact that I'm not on a different branch and pushed random things to this PR. They've been matched into `master` and can be safely ignored™

2021-01-16 05:19 UTC, doamatto commented on privacy.md
> +- the content ID of what you favourited (used to store your favourites for whenever you need them)
Describe how this is stored with CloudKit when using Sign In With Apple

2021-01-16 05:19 UTC, doamatto commented on privacy.md
> +If you sign in with [Apple](https://www.apple.com/legal/privacy/en-ww/), you are under their privacy policy. Review to know what you're getting yourself into.
Fix wording to be clearer

2021-01-16 05:19 UTC, doamatto commented on privacy.md
> +**TODO: See if there are other things that need to go here**
Resolve TODO section ( needs researching )

2021-02-09 01:07 UTC, cyckl commented on privacy.md
> +When you download the application, you need to make an account. If you sign up with Apple, Apple gives us the following data:
It's probably better to make it seem that we aren't receiving any data ("give" might have that connotation), so saying that Apple is simply allowing access fixes that issue.
```suggestion
When you download the application, you need to make an account. If you sign up with Apple, Apple will allow us access to the following data:
```

2021-02-09 01:11 UTC, cyckl commented on privacy.md
> +- your email address (we ignore this data, as well)
Seems unclear to specify this for all the types of data that we are allowed access to, would be best to simply tell the user a) what data we could access and b) what we do with it
```suggestion
- your first and last name
- your email address
Even though Apple allows us access to the above-mentioned, we do not access or use any of this data when you access Mello.
```

2021-02-09 01:51 UTC, cyckl reviewed
Added a few fixes that I felt were important to clarity

2021-02-09 01:51 UTC, cyckl commented on privacy.md
> +- your email address (we ignore this data, as well)
Also, just from reading this, it's unclear specifically how we do authentication with Apple if we do not use any of the data provided? Is there a token or unique identifier that they also provide? If there is, it's best that we add that to the privacy policy under what's collected.

2021-02-09 01:51 UTC, cyckl commented on privacy.md
> +- a password that you provide (used for login)
Would be best to change wording from password "recovery" to "resets", to make it clear that passwords are not stored in their original form. To add on to that it's would also be nice to add on to the password entry by clarifying that it's not stored but instead hashed securely.
```suggestion
- your email address (used for logging in and password resets)
- a password that you provide (used for logging in, securely hashed and salted)
```

2021-02-09 01:51 UTC, cyckl commented on privacy.md
> +- a password that you provide (used for login)
did not mean to make this a review

2021-02-09 01:51 UTC, cyckl commented on privacy.md
> +If you sign in with [Apple](https://www.apple.com/legal/privacy/en-ww/), you are under their privacy policy. Review to know what you're getting yourself into.
Best to remove or adjust the last sentence, seems slightly snarky. Would also be good to move the privacy policy link to actually be for the words "privacy policy".
```suggestion
If you sign in with Apple, you are under their [privacy policy](https://www.apple.com/legal/privacy/en-ww/). Review to know their data policies.
```
Or optionally:
```suggestion
If you sign in with Apple, you are under their [privacy policy](https://www.apple.com/legal/privacy/en-ww/).
```

2021-02-09 01:51 UTC, cyckl commented on privacy.md
> +The U.S. government could request information from us. We will only provide data if they provide us a legal order such as a subpoena. When they provide us with such order and an email address to find
A user would probably feel slightly better if we explain why the U.S. government has the authority to request user data.
```suggestion
Mello, it's servers, and it's members are under the jurisdiction of the United States. This means that the U.S. government has the ability to request user information from us. Due to our commitment to privacy, we would only provide data if they provide us with a legal order such as a subpoena. Should they provide us with such order and a valid email address to find the user in question, we will still be unable to give them any information because:
```

2021-02-09 01:51 UTC, cyckl commented on privacy.md
> +In the event of a data breach, we will send out an email address, regardless of if you were affected or not, with password reset notifications, following information pertaining to what things may hav
Grammar fixes
```suggestion
In the event of a data breach, we will send out an email notification, regardless of if you were affected or not, with password reset notifications, following information pertaining to what things may have been compromised. This will all be done as soon as we find said breach. Once this issue is patched, we may release information on the issue as well as a write-up on how we fixed it on GitHub.
```

2021-02-09 01:52 UTC, cyckl commented
Interesting, it seems to have added a few which were not inline with the singular review. Apologies

2021-02-09 04:15 UTC, doamatto commented on privacy.md
> +- your email address (we ignore this data, as well)
Apple does provide us with an access token of sorts for OAUTH that's meant to be used in place of the hash you would for normal logins (afaik). It's documented [here](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/authenticating_users_with_sign_in_with_apple); I'll try to better document how we use this token when I get a chance

2021-02-09 04:42 UTC, cyckl commented on privacy.md
> +**TODO: See if there are other things that need to go here**
GDPR also requires simply being able to request and view all available data on yourself, if you feel the need to add that

2021-02-09 21:50 UTC, doamatto commented on privacy.md
> +**TODO: See if there are other things that need to go here**
Added request to view in f1f2243

2021-02-09 21:59 UTC, doamatto commented on privacy.md
> +- your email address (we ignore this data, as well)
Clarified in 23de3fe

2021-02-23 19:26 UTC, cyckl requested changes

2021-02-23 19:26 UTC, cyckl commented on privacy.md
> +- a unique token for us for authentication (we use this in place of an email address or password).
This does not make sense given that it's using an email address. Are you referring to sending an email to the user every time they want to login and authenticating them through a link attached in the email?

2021-02-23 19:26 UTC, cyckl commented on privacy.md
> +Your settings that you use in the app will automatically sync between devices to give a seamless experience. This is stored with your content ID
```suggestion
Your settings that you use in the app will automatically sync between devices to give a seamless experience. This is stored alongside your favourited content IDs.
```
"with your content ID" is singular, might be slightly confusing / vague

2021-02-23 19:26 UTC, cyckl commented on privacy.md
> +- your first and last name (if you signed in with Apple).
1. Is this data required for us / Magic to collect?
2. If not, does Apple automatically share this data or can we prevent ourselves / Magic from collecting it

2021-02-23 19:26 UTC, cyckl commented on privacy.md
>  If you sign up with an email address, we collect the following data:
```suggestion
Alternatively, if you sign up with an email address, we collect the following data:
```
References last option, reinforcing that there are two options

2021-02-23 20:08 UTC, doamatto commented on privacy.md
> +- a unique token for us for authentication (we use this in place of an email address or password).
Exactly; you get an email from Magic with a one-time link that expires after 10 minutes to login.

2021-02-23 20:11 UTC, doamatto commented on privacy.md
> +- your first and last name (if you signed in with Apple).
1. Email addresses do need to be collected to generate hashes for users and allow for authentication
2. Apple, just like how we get passed someone's name and email through Sign in with Apple, passes that data through Magic to allow for auth. It may be possible to tell users prior that they might want to use fake information for their name and the "Hide my email" functionality, but it doesn't seem practical

2021-02-24 23:24 UTC, cyckl commented on privacy.md
> +- a unique token for us for authentication (we use this in place of an email address or password).
Seems good.

2021-02-24 23:24 UTC, cyckl commented on privacy.md
> +- your first and last name (if you signed in with Apple).
I see, well if Magic collects it automatically then it makes sense

2021-02-24 23:24 UTC, cyckl approved these changes

2021-06-17 12:48 UTC, cyckl commented on privacy.md
> +Truth be told: there's no be all and end all to protect your data. But, we do our best to use modern-day encryption methods as well as strict HSTS, DNSSEC, and CSP to ensure your experience is the wa
Probably best to state this fact somewhere in the beginning of the document then just talk about "what if" the user has an account with us, and what that means for their data

2021-06-17 14:34 UTC, doamatto commented on privacy.md
> +Truth be told: there's no be all and end all to protect your data. But, we do our best to use modern-day encryption methods as well as strict HSTS, DNSSEC, and CSP to ensure your experience is the wa
This has now been adjusted to be in the talks of data collection in the first place.

2021-06-18 16:27 UTC, doamatto commented
Once this is approved, it will be blocked by #21. Fortunately, it's just a matter of changing YAML to TOML for the frontmatter. All the templating was already over there for other things.

2021-06-18 19:35 UTC, cyckl approved these changes

2021-06-18 19:42 UTC, closed without merging